name: Code Security Audit

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-3 network-manager python3-gi libdbus-1-dev python3-gi-cairo gir1.2-gtk-3.0 dbus libusb-dev libdbus-1-dev libglib2.0-dev libudev-dev libical-dev libreadline-dev libgirepository1.0-dev python3-cairo-dev libcairo2 libcairo2-dev

    - name: Install poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.9.0

    - name: Install dependencies
      run: |
        poetry install --with dev

    - name: Run bandit against code base
      run: |
        poetry run bandit -r gatewayconfig -c pyproject.toml
        poetry run bandit -r lib -c pyproject.toml
